# Generated by Django 5.1.4 on 2025-02-21 22:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
