# Generated by Django 5.0.7 on 2024-10-16 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='SkillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('requirement_level', models.CharField(choices=[('required', 'Required'), ('preferred', 'Preferred'), ('bonus', 'Bonus')])),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.position')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.skill')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='skills',
            field=models.ManyToManyField(through='company.SkillDetail', to='company.skill'),
        ),
        migrations.AddField(
            model_name='position',
            name='tasks',
            field=models.ManyToManyField(to='company.task'),
        ),
        migrations.CreateModel(
            name='TraitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('requirement_level', models.CharField(choices=[('required', 'Required'), ('preferred', 'Preferred'), ('bonus', 'Bonus')])),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.position')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.trait')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='traits',
            field=models.ManyToManyField(through='company.TraitDetail', to='company.trait'),
        ),
    ]
