# Generated by Django 5.0.4 on 2024-04-17 20:59

import datetime
import django.db.models.deletion
import hiring_companies.models.job_requirements
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_seekers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerField',
            fields=[
                ('careerfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='job_seekers.careerfield')),
            ],
            bases=('job_seekers.careerfield',),
        ),
        migrations.CreateModel(
            name='CareerSubfield',
            fields=[
                ('careersubfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='job_seekers.careersubfield')),
            ],
            bases=('job_seekers.careersubfield',),
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='job_seekers.industry')),
            ],
            bases=('job_seekers.industry',),
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField()),
                ('county', models.CharField(null=True)),
                ('state', models.CharField(null=True)),
                ('country', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='job_seekers.skill')),
            ],
            bases=('job_seekers.skill',),
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('trait_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='job_seekers.trait')),
            ],
            bases=('job_seekers.trait',),
        ),
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('worktask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='job_seekers.worktask')),
            ],
            bases=('job_seekers.worktask',),
        ),
        migrations.CreateModel(
            name='JobRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_or_hybrid', models.BooleanField(default=False)),
                ('required_onsite_time', models.DurationField(default=datetime.timedelta(days=5))),
                ('relocation_assistance_available', models.BooleanField(default=False)),
                ('maximum_relocation_distance', models.SmallIntegerField(null=True)),
                ('distance_measurement', models.CharField(choices=[('mi', 'mi'), ('km', 'km')], max_length=2, null=True)),
                ('maximum_relocation_assistance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pay_low', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pay_high', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('position_days_and_hours', models.JSONField(default=hiring_companies.models.job_requirements.JobRequirements.default_position_days_and_hours)),
                ('start_date_requested', models.DateField(default=datetime.date.today)),
                ('position_availability_start_date', models.DateField(default=datetime.date.today)),
                ('position_availability_end_date', models.DateField(null=True)),
                ('career_fields_available', models.ManyToManyField(related_name='jobs_available', to='hiring_companies.careerfield')),
                ('career_subfields_available', models.ManyToManyField(related_name='jobs_available', to='hiring_companies.careersubfield')),
                ('industrys_available', models.ManyToManyField(related_name='jobs_available', to='hiring_companies.industry')),
                ('job_locations', models.ManyToManyField(related_name='jobs_available', to='hiring_companies.joblocation')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_original', models.CharField()),
                ('company_name_latinized', models.CharField(null=True)),
                ('job_requirements', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hiring_companies.jobrequirements')),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField()),
                ('required', models.BooleanField(default=False)),
                ('job_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring_companies.jobrequirements')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desired_skills', to='hiring_companies.skill')),
            ],
        ),
        migrations.AddField(
            model_name='jobrequirements',
            name='skills',
            field=models.ManyToManyField(related_name='jobs_available', through='hiring_companies.SkillLevel', to='hiring_companies.skill'),
        ),
        migrations.CreateModel(
            name='TraitLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField()),
                ('required', models.BooleanField(default=False)),
                ('job_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring_companies.jobrequirements')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desired_traits', to='hiring_companies.trait')),
            ],
        ),
        migrations.AddField(
            model_name='jobrequirements',
            name='traits',
            field=models.ManyToManyField(related_name='jobs_available', through='hiring_companies.TraitLevel', to='hiring_companies.trait'),
        ),
        migrations.AddField(
            model_name='jobrequirements',
            name='work_tasks',
            field=models.ManyToManyField(related_name='jobs_available', to='hiring_companies.worktask'),
        ),
    ]
