# Generated by Django 5.0.4 on 2024-05-10 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequirements',
            old_name='start_date',
            new_name='start_date_earliest',
        ),
        migrations.AddField(
            model_name='jobrequirements',
            name='start_date_latest',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
