# Generated by Django 5.0.4 on 2024-05-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_companies', '0002_rename_start_date_jobrequirements_start_date_earliest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequirements',
            name='maximum_commute',
            field=models.SmallIntegerField(blank=True, default=100, null=True),
        ),
    ]
