# Generated by Django 5.0.4 on 2024-04-12 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_companies', '0003_joblocation'),
        ('job_seekers', '0002_preferences_desired_onsite_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerField',
            fields=[
                ('careerfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='job_seekers.careerfield')),
            ],
            bases=('job_seekers.careerfield',),
        ),
        migrations.CreateModel(
            name='CareerSubfield',
            fields=[
                ('careersubfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='job_seekers.careersubfield')),
            ],
            bases=('job_seekers.careersubfield',),
        ),
        migrations.CreateModel(
            name='CompanyField',
            fields=[
                ('companyfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='job_seekers.companyfield')),
            ],
            bases=('job_seekers.companyfield',),
        ),
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('worktask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='job_seekers.worktask')),
            ],
            bases=('job_seekers.worktask',),
        ),
    ]
