# Generated by Django 5.0.4 on 2024-04-12 18:41

import datetime
import hiring_companies.models.job_requirements
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_companies', '0004_careerfield_careersubfield_companyfield_worktask'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_or_hybrid', models.BooleanField(default=False)),
                ('required_onsite_time', models.DurationField(default=datetime.timedelta(days=5))),
                ('relocation_assistance_available', models.BooleanField(default=False)),
                ('maximum_relocation_distance', models.SmallIntegerField(null=True)),
                ('distance_measurement', models.CharField(choices=[('mi', 'mi'), ('km', 'km')], max_length=2, null=True)),
                ('maximum_relocation_assistance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pay_low', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pay_high', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('position_days_and_hours', models.JSONField(default=hiring_companies.models.job_requirements.JobRequirements.default_position_days_and_hours)),
                ('start_date_requested', models.DateField(default=datetime.date.today)),
                ('position_availability_start_date', models.DateField(default=datetime.date.today)),
                ('position_availability_end_date', models.DateField(null=True)),
                ('career_fields_available', models.ManyToManyField(related_name='jobs_available', to='hiring_companies.careerfield')),
                ('career_subfields_available', models.ManyToManyField(related_name='jobs_available', to='hiring_companies.careersubfield')),
                ('company_field', models.ManyToManyField(related_name='jobs_available', to='hiring_companies.companyfield')),
                ('job_locations', models.ManyToManyField(related_name='jobs_available', to='hiring_companies.joblocation')),
                ('work_tasks', models.ManyToManyField(related_name='jobs_available', to='hiring_companies.worktask')),
            ],
        ),
    ]
