# Generated by Django 5.0.4 on 2024-04-12 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_companies', '0005_jobrequirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequirements',
            name='required_skills',
            field=models.ManyToManyField(related_name='jobs_available', to='hiring_companies.skill'),
        ),
        migrations.AddField(
            model_name='jobrequirements',
            name='required_traits',
            field=models.ManyToManyField(related_name='jobs_available', to='hiring_companies.trait'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_original', models.CharField()),
                ('company_name_latinized', models.CharField(null=True)),
                ('job_locations', models.ManyToManyField(related_name='companies', to='hiring_companies.joblocation')),
                ('job_requirements', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hiring_companies.jobrequirements')),
            ],
        ),
    ]
