# Generated by Django 5.0.4 on 2024-04-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_companies', '0006_jobrequirements_required_skills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrequirements',
            old_name='company_field',
            new_name='company_fields_available',
        ),
    ]
