# Generated by Django 5.0.4 on 2024-04-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_companies', '0007_rename_company_field_jobrequirements_company_fields_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='job_locations',
        ),
    ]
