# Generated by Django 5.0.4 on 2024-05-01 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hiring_companies', '0001_initial'),
        ('job_seekers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiring_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring_companies.company')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seekers.user')),
            ],
        ),
    ]
