# Generated by Django 5.0.3 on 2024-04-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_original', models.CharField()),
                ('full_name_latinized', models.CharField(null=True)),
                ('sort_by', models.JSONField()),
            ],
        ),
    ]
