# Generated by Django 5.0.3 on 2024-04-10 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0002_skill_user_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField()),
                ('city', models.CharField()),
                ('county', models.CharField(null=True)),
                ('state', models.CharField(null=True)),
                ('country', models.CharField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_seekers.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='traits',
            field=models.ManyToManyField(to='job_seekers.trait'),
        ),
    ]
