# Generated by Django 5.0.4 on 2024-05-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='maximum_commute',
            field=models.SmallIntegerField(blank=True, default=100, null=True),
        ),
    ]
