# Generated by Django 5.0.3 on 2024-04-10 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0003_trait_address_user_traits'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_seekers.address'),
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote', models.BooleanField(default=False)),
                ('relocate', models.BooleanField(default=False)),
                ('relocation_distance', models.SmallIntegerField(null=True)),
                ('distance_measurement', models.CharField(choices=[('mi', 'mi'), ('km', 'km')], max_length=2, null=True)),
                ('relocation_assistance_needed', models.BooleanField(default=False)),
                ('relocation_assistance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('non_preferred_career_fields', models.ManyToManyField(related_name='non_preferred_by', to='job_seekers.careerfield')),
                ('preferred_career_fields', models.ManyToManyField(related_name='preferred_by', to='job_seekers.careerfield')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_seekers.preferences'),
        ),
    ]
